---
- name: Configure HashiCorp repository
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    owner: root
    group: root
    mode: "0644"

- name: Install Terraform
  ansible.builtin.dnf5:
    name: terraform
    state: present
