---
- name: Configure MongoDB 8.0 Enterprise repository
  ansible.builtin.yum_repository:
    name: mongodb-enterprise-8.0
    description: MongoDB Enterprise Repository
    baseurl: "https://repo.mongodb.com/yum/redhat/9/mongodb-enterprise/8.0/$basearch/"
    enabled: true
    gpgcheck: true
    gpgkey: https://pgp.mongodb.com/server-8.0.asc

- name: Configure MongoDB 8.0 Community repository disabled by default
  ansible.builtin.yum_repository:
    name: mongodb-org-8.0
    description: MongoDB Community Repository
    baseurl: "https://repo.mongodb.org/yum/redhat/9/mongodb-org/8.0/$basearch/"
    enabled: false
    gpgcheck: true
    gpgkey: https://pgp.mongodb.com/server-8.0.asc

- name: Install MongoDB shell and Enterprise tools
  ansible.builtin.dnf5:
    name: "{{ fedora_workstation_mongodb_packages }}"
    state: present
